### ISSUE TITLE
Invidious official domain has now moved to a new one (https://invidious.io)

### ISSUE THREAD

**Issue by Mennaruuk** [git-bruh/invidious-viewer#2]
**https://invidious.io is the new URL**. https://invidio.us is now deprecated according to [the project's recent announcement.](https://github.com/iv-org/invidious/issues/1694)

"invidio.us is now deprecated, invidious.io is the new domain.

The invidious-redirect website ( invidio.us ) is now https://redirect.invidious.io/

The instance API ( instances.invidio.us ) is now https://api.invidious.io/

The uptimerobot page ( uptime.invidio.us ) is now https://uptime.invidious.io/

https://git.invidious.io/ redirects to the Github page of the project: https://github.com/iv-org/invidious/

https://docs.invidious.io/ redirects to the documentation website of the project: https://github.com/iv-org/documentation/

https://invidious.io/ will become in the future a "project presentation" page (like https://searx.me/ ), we will use a markdown framework like Hugo."

**Comment by git-bruh** [comment]
This doesn't affect the project, since `invidious.snopyta.org` is set as the default instance (configurable), but thanks for the info @Mennaruuk !
