### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jgarte** [git-bruh/invidious-viewer#3]
Hi, are there any plans to make a release?

I'd like to package this for GNU/Guix and it would have a higher chance of being accepted upstream if this package has releases.

all best

**Comment by git-bruh** [comment]
Hi, I haven't worked on this for a while now, not sure if it even works anymore :p
Either way it's pretty featureless, for example it doesn't reattempt to open a video if YouTube blocks the current instance so I feel it's not really worth creating a package for.
I don't have any plans to work on this project.

**Comment by git-bruh** [comment]
See https://github.com/pystardust/ytfzf aswell, It has an invidious backend.
